.PHONY: \
	run-scripts \
	securty \
	lint \
	format \

.DEFAULT_GOAL:=help

SHELL=bash

SCRIPTS_DIR := scripts

format:
	black $(SCRIPTS_DIR)/*.py

lint:
	flake8 $(SCRIPTS_DIR)/*.py --count --select=E9,F63,F7,F82 --show-source --statistics
	flake8 $(SCRIPTS_DIR)/*.py --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics

securty:
	bandit -r $(SCRIPTS_DIR)/*.py --tests B101, B301, B303, B602, B701

run-scripts:
	@echo "Running Python scripts..."
	@for script in $(wildcard $(SCRIPTS_DIR)/*.py); do \
		echo "Executing $$script"; \
		python $$script; \
	done