.PHONY: all install venv format lint securty run-scripts clean

VENV := venv

SCRIPTS_DIR := scripts

install: 
	@echo "Installing requirements..."
		python3.10 -m venv $(VENV) && \
		source venv/bin/activate && \
		pip install --upgrade pip && \
		pip install -r requirements.txt


format: venv
	@echo "Running Python scripts..."
	@for script in $(wildcard $(SCRIPTS_DIR)/*.py); do \
		echo "Executing $$script"; \
		black $$script; \
	done

lint: venv
	@echo "Running Python scripts..."
	@for script in $(wildcard $(SCRIPTS_DIR)/*.py); do \
		echo "Executing $$script"; \
		flake8 $$script --count --select=E9,F63,F7,F82 --show-source --statistics; \
		flake8 $$script --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics; \
	done

securty: venv
	@echo "Running Python scripts..."
	@for script in $(wildcard $(SCRIPTS_DIR)/*.py); do \
		echo "Executing $$script"; \
		bandit -r $$script --tests B101, B301, B303, B602, B701; \
	done

run-scripts: venv
	@echo "Running Python scripts..."
	@for script in $(wildcard $(SCRIPTS_DIR)/*.py); do \
		echo "Executing $$script"; \
		python $$script; \
	done

clean:
	rm -rf $(VENV)
	find . -type f -name '*.pyc' -delete



all: install venv format lint securty run-scripts clean
